### ISSUE TITLE
Allow setting `DJANGO_SECRET_KEY` from an existing secret

### ISSUE THREAD

**Issue by voldemortensen** [Flagsmith/flagsmith-charts#134]
This can be done with backwards compatibility with this in `_api_environment.yaml`:
```yaml
- name: DJANGO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      {{- if .Values.api.secretKeyFromExistingSecret.enabled }}
      name: {{ .Values.api.secretKeyFromExistingSecret.name }}
      key: {{ .Values.api.secretKeyFromExistingSecret.key }}
      {{- else }}
      name: {{ template "flagsmith.fullname" . }}
      key: DJANGO_SECRET_KEY
      {{- end }}
```

and this in `values.yaml`:
```yaml
api:
  ...
  secretKey: null
  secretKeyFromExistingSecret:
    enabled: false
    name: null
    key: null
```
