### ISSUE TITLE
Frontend Ingress allows for path configuration but only root path is supported

### ISSUE THREAD

**Issue by kyleb4020** [Flagsmith/flagsmith-charts#138]
I used the helmchart values to specify the ingress for the frontend as follows:
```
ingress:
  frontend:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    ingressClassName: ingress
    hosts:
      - host: '*.[MY-DOMAIN]'
        paths: 
        -  /flagsmith(/|$)(.*)
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  api:
    enabled: false
    annotations: {}
    ingressClassName: null
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
```
This results in DOM errors when trying to navigate to my flagsmith instance. The frontend code attempts to load all resources from the root (`/`) path instead of the path specified by the ingress frontend.

I reached out via discord to see about configuring the frontend to hit the subfolder instead of the root and was told this is not supported. The Flagsmith frontend is indeed hosted at the path I specified, but is not functional because none of the files are found where the index is looking for them. If I manually take the url of any of the resources index is referencing and I insert the subfolder into the url, the file loads appropriately so I know the ingress is working.

The documentation needs to be updated and the helmcharts should be updated to not support any path specification until subfolders are supported for the frontend.
