### ISSUE TITLE
Using K8s helm chart in google cloud platform with cloud sql, keeps on giving error database not ready for connections

### ISSUE THREAD

**Issue by nishant-shah-social** [Flagsmith/flagsmith-charts#141]
### Summary
We have our infrastructure in Google cloud Kubernetes.
While trying to setup flagsmith in GCP, I keep on getting this error and the api pod remain in CrashLoopBackOff
```
core.management.commands.waitfordb WARNING Database not yet ready for connections.
```
Following is the details of my setup:-

- Using the latest version of helmchart present [here](https://artifacthub.io/packages/helm/flagsmith/flagsmith), i.e. 0.20.0
- Using Google Cloud SQL(database external) instead of local Postgresql
- Have taskprocessor enabled

After deploying the chart with required values, I keep on getting the above error for api pod
Below is the values.yaml file 
```
    api:
      image:
        repository: flagsmith/flagsmith-api
        tag: 2.57.0
        imagePullPolicy: IfNotPresent
        imagePullSecrets: []
      separateApiAndFrontend: true
      replicacount: 2
      deploymentStrategy: null
      podAnnotations: {}
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      podLabels: {}
      secretKeyFromExistingSecret:
        enabled: true
        name: flagsmith-credentials
        key: django_secret_key
      nodeSelector: {}
      tolerations: []
      affinity: {}
      podSecurityContext: {}
      defaultPodSecurityContext:
        enabled: true
      livenessProbe:
        path: /health
        failureThreshold: 5
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 2
      readinessProbe:
        path: /health
        failureThreshold: 10
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 2
      statsd:
        enabled: false
      influxdbSetup:
        enabled: false

    frontend:
      enabled: true
      image:
        repository: flagsmith/flagsmith-frontend
        tag: 2.57.0
        imagePullPolicy: IfNotPresent
        imagePullSecrets: []
      replicacount: 1
      deploymentStrategy: null
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 300m
          memory: 300Mi
      apiProxy:
        enabled: true
      extraEnv:
        FLAGSMITH_API_URL: 'https://flagsmith.domain/api/v1/'
      extraEnvFromSecret: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
      podSecurityContext: {}
      defaultPodSecurityContext:
        enabled: true
      livenessProbe:
        failureThreshold: 20
        initialDelaySeconds: 20
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      readinessProbe:
        failureThreshold: 20
        initialDelaySeconds: 20
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10

# See https://docs.flagsmith.com/deployment/task-processor
# uses the same image as api but with different entrypoint
    taskProcessor:
      enabled: true
      livenessProbe:
        failureThreshold: 5
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 2
      readinessProbe:
        failureThreshold: 10
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 2
      podAnnotations: {}
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 300m
          memory: 300Mi
      podLabels: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
      podSecurityContext: {}
      defaultPodSecurityContext:
        enabled: true

    influxdb2:
      enabled: false

    postgresql:
      enabled: false

    databaseExternal:
      enabled: true
      url: postgresql://dbproxy:5432/flagsmith
      type: postgres
      host: dbproxy
      port: 5432
      database: flagsmith
      username: flagsmith
      password:
        valueFrom:
          secretKeyRef:
            key: db_password
            name: flagsmith-credentials
      urlFromExistingSecret:
        enabled: false
        name: null
        key: null

    service:
      api:
        type: ClusterIP
        port: 8000
        annotations: {}
      frontend:
        type: ClusterIP
        port: 8080
        annotations: {}

    ingress:
      frontend:
        enabled: true
        annotations: {}
        ingressClassName: null
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
        hosts:
          - host: flagsmith.domain.dev
            paths:
              - /
        tls: []
      api:
        enabled: true
        annotations: {}
        ingressClassName: null
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
        hosts:
          - host: flagsmith.domain.dev
            paths:
              - /api/
              - /health/
        tls: []
```
