### ISSUE TITLE
chart forces svc.cluster.local in service names

### ISSUE THREAD

**Issue by deefdragon** [Flagsmith/flagsmith-charts#151]
I have deployed my cluster with a custom domain. This results in svc.example.com as my root for all of my services, meaning that the current default deployed cluster, which uses svc.cluster.local can not boot the api pods.

**Comment by dabeeeenster** [comment]
Can you provide more details as well as your values file?

**Comment by deefdragon** [comment]
```yml
"api":
  "livenessProbe":
    "timeoutSeconds": 4
"ingress":
  "api":
    "enabled": true
    "hosts":
    - "host": "flags.example.com"
      "paths":
      - "/"
  "frontend":
    "enabled": true
    "hosts":
    - "flagsmith.example.com"
```

The issue is that the [env value in the deployment](https://github.com/Flagsmith/flagsmith-charts/blob/main/charts/flagsmith/templates/deployment-api.yaml#L86) generated for the influx connection, [INFLUXDB_URL](https://github.com/Flagsmith/flagsmith-charts/blob/main/charts/flagsmith/templates/_api_environment.yaml#L23) has a [hardcoded domain ending](https://github.com/Flagsmith/flagsmith-charts/blob/main/charts/flagsmith/templates/_helpers.tpl#L202C72-L202C90).

This should be solvable by adding a config option to the values to override `svc.cluster.local` with some other dns value. I am unsure if this way that other charts do this however, and what the normal method for dealing with this situation is. I suspect bitnami has had to deal with this exact issue previously, so Id reference them.
