### ISSUE TITLE
[ASK] How to set google oauth with this charts

### ISSUE THREAD

**Issue by Zaimeth** [Flagsmith/flagsmith-charts#165]
Hello I am not very familiar with using helm, and want to use a flagsmith helm chart for my use, and I am very confused about how exactly to pair google oauth on this helm chart. is there anyone who can help me? thank u

Here is an example that I am currently using in configuring it, but it seems that I am still wrong

```
api:
  image:
    repository: flagsmith/flagsmith-api
    tag: null # defaults to .Chart.AppVersion
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  separateApiAndFrontend: true
  replicacount: 1
  deploymentStrategy: null
  podAnnotations: {}
  resources: 
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  podLabels: 
    service_name: flagsmith
    service_type: python
  extraEnv: 
    ExtraEnvFromSecret:
      oauth_google: 
          clientId : xxxxx
          apiKey: xxxx
  ```
  the goal is I hope later I can login flagsmith using a google account 
  I know this question might be a bit stupid, but if anyone knows, I hope someone can help me to understand better. thank u 🙏🙏
