### ISSUE TITLE
Port is malformed in secret using databaseExternal.port

### ISSUE THREAD

**Issue by ncalibey** [Flagsmith/flagsmith-charts#57]
When bringing your own database for the api server and setting the fields individually, the `databaseExternal.port` value ends up malformed in the secret. For example, this configuration:
```yaml
databaseExternal:
  enabled: true
  type: postgres
  host: mypostgreshost.com
  database: postgres
  username: postgres
  password: pgpass
  port: 5432
```

Is encoded in the secret thusly:
```
postgres://postgres:pgpass@mypostgreshost.com:%!s(float64=5432)/postgres
```

This is true even if you don't specify the `port` field so that it defaults to `5432`. However, quoting the value (i.e. `port: "5432"`) will result in the correct connection string. I believe this is because in the helper template, the verb being used is `%s` whereas maybe `%d` would be more appropriate. Alternatively, it could be quoted in the template.

While putting the port in quotes isn't a big deal, the [current documentation](https://docs.flagsmith.com/deployment/kubernetes#database-configuration) shows it unquoted, and hence the confusion. That said, perhaps there's something on my end that I'm missing and am configuring it incorrectly. Thanks for the chart/product!
